[project]
name = "swap-shop-contracts"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.ft-trait]
path = "contracts/ft-trait.clar"
depends_on = []

[contracts.nft-trait]
path = "contracts/nft-trait.clar"
depends_on = []

[contracts.private-sale-v1]
path = "contracts/private-sale-v1.clar"
depends_on = ["nft-trait", "swap-shop-commission-trait"]

[contracts.sip009-nft]
path = "contracts/sip009-nft.clar"
depends_on = ["nft-trait"]

[contracts.swap-shop-commission]
path = "contracts/swap-shop-commission.clar"
depends_on = []

[contracts.swap-shop-commission-noop]
path = "contracts/swap-shop-commission-noop.clar"
depends_on = []

[contracts.swap-shop-commission-trait]
path = "contracts/swap-shop-commission-trait.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
