[project]
name = "swapshop"
authors = []
description = ""
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"

[contracts.sip009-test]
path = "contracts/sip009-test.clar"

[contracts.sip010-test]
path = "contracts/sip010-test.clar"

[contracts.swapshop-private-trade-v1]
path = "contracts/swapshop-private-trade-v1.clar"

[contracts.swapshop-whitelist-v1]
path = "contracts/swapshop-whitelist-v1.clar"

[contracts.traits]
path = "contracts/traits.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
